### ISSUE TITLE
Arch package is just salt

### ISSUE THREAD

**Issue by txomon** [salt-formulas/salt-formula-salt#62]
I have seen that the package referenced by this formula is `salt-zmq`, this shouldn't be like that, as it was replaced by `salt` package in the Arch Linux repo. https://www.archlinux.org/packages/community/any/salt/

Lines:
https://github.com/salt-formulas/salt-formula-salt/blob/master/salt/map.jinja#L31
https://github.com/salt-formulas/salt-formula-salt/blob/master/salt/map.jinja#L94

And I haven't tried api or control but they are probably wrong too pointing somewhere else...

**Comment by fpytloun** [comment]
Thank you for your report. Please feel free to submit pull request.

**Comment by txomon** [comment]
Closed in #63
